ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_credential_version_" TO "supplier_reservation_ops_credential_version_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_request_fingerprint" TO "supplier_reservation_ops_request_fingerprint_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_offer_fingerprint_c" TO "supplier_reservation_ops_offer_fingerprint_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_terms_fingerprint_c" TO "supplier_reservation_ops_terms_fingerprint_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_payload_fingerprint" TO "supplier_reservation_ops_payload_fingerprint_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_provider_reference_" TO "supplier_reservation_ops_provider_reference_state_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_supplier_confirmati" TO "supplier_reservation_ops_confirmation_reference_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_provider_recovery_r" TO "supplier_reservation_ops_recovery_reference_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_failure_state_contr" TO "supplier_reservation_ops_failure_state_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_review_acceptance_c" TO "supplier_reservation_ops_review_acceptance_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_selection_machine_r" TO "supplier_reservation_ops_selection_token_check";
ALTER TABLE "hospitality_supplier_reservation_operations"
  RENAME CONSTRAINT "hospitality_supplier_reservation_operations_provider_machine_re" TO "supplier_reservation_ops_provider_token_check";

ALTER TABLE "hospitality_supplier_reservation_attempts"
  RENAME CONSTRAINT "hospitality_supplier_reservation_attempt_provider_request_clock" TO "supplier_reservation_attempt_provider_clock_check";
ALTER TABLE "hospitality_supplier_reservation_attempts"
  RENAME CONSTRAINT "hospitality_supplier_reservation_attempt_provider_evidence_chec" TO "supplier_reservation_attempt_provider_evidence_check";
ALTER TABLE "hospitality_supplier_reservation_attempts"
  RENAME CONSTRAINT "hospitality_supplier_reservation_attempt_review_failure_code_ch" TO "supplier_reservation_attempt_review_failure_check";
ALTER TABLE "hospitality_supplier_reservation_attempts"
  RENAME CONSTRAINT "hospitality_supplier_reservation_attempts_provider_correlation_" TO "supplier_reservation_attempt_correlation_control_check";

ALTER TABLE "hospitality_supplier_reservation_review_acceptance_history"
  RENAME CONSTRAINT "hospitality_supplier_reservation_review_acceptance_history_cont" TO "supplier_review_acceptance_history_contract_check";

ALTER INDEX "hospitality_supplier_reservation_operations_org_provider_refere"
  RENAME TO "supplier_reservation_ops_provider_ref_key";
ALTER INDEX "hospitality_supplier_reservation_operations_org_status_created_"
  RENAME TO "supplier_reservation_ops_status_created_idx";
ALTER INDEX "hospitality_supplier_reservation_operations_org_integration_sta"
  RENAME TO "supplier_reservation_ops_integration_status_idx";
ALTER INDEX "hospitality_supplier_reservation_attempts_org_reservation_seque"
  RENAME TO "supplier_reservation_attempts_sequence_key";
ALTER INDEX "hospitality_supplier_reservation_attempts_org_reservation_start"
  RENAME TO "supplier_reservation_attempts_reservation_started_idx";
ALTER INDEX "hospitality_supplier_reservation_attempts_org_status_started_id"
  RENAME TO "supplier_reservation_attempts_status_started_idx";
